name: My Workflow
on:
  push:
    branches:
      - main

jobs:
  typedoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: "doriancrutcher/repo-a"
          ref: "main"

      - name: Generate documentation
        run: |
          npx typedoc index.ts

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: typedocs
          path: ./docs/

  upload:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    needs: typedoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: "doriancrutcher/repo-f"
          ref: "main"

      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: typedocs
          path: ./docs-input/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add typedoc documentation"
          commit_options: "--no-verify"
          tagging_message: "v1.0.0"
